"""empty message

Revision ID: 2c0aebebf5bf
Revises: 891094dfe20c
Create Date: 2024-12-11 19:24:24.655067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0aebebf5bf'
down_revision = '891094dfe20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
